version: '3.8'

services:
  
  postgres:
    image: postgres
    ports:
      - 5432:5432
    environment:
      - POSTGRES_PASSWORD=PASSWORD1234
    volumes:
      - postgres_data:/var/lib/postgresql/data
  
  backend:
    build:
      dockerfile: docker/dockerfile.backend
      context: .
    
    ports:
      - 3001:3001
    
    environment:
      - DATABASE_URL=postgresql://postgres:PASSWORD1234@postgres:5432/postgres
    
    depends_on:
      - postgres
  
  web:
    build:
      dockerfile: docker/dockerfile.web
      context: .
    
    ports:
      - 3000:3000
    
    environment:
      - DATABASE_URL=postgresql://postgres:PASSWORD1234@postgres:5432/postgres
    
    depends_on:
      - postgres
  
  ws:
    build:
      dockerfile: docker/dockerfile.ws
      context: .
    
    ports:
      - 3002:3002
    
    environment:
      - DATABASE_URL=postgresql://postgres:PASSWORD1234@postgres:5432/postgres
    
    depends_on:
      - postgres
    
volumes:
  postgres_data: