FROM node:22-alpine

RUN npm install -g pnpm

WORKDIR /app

COPY package.json package.json
COPY ./packages ./packages
COPY pnpm-lock-yaml pnpm-lock-yaml
COPY pnpm-workspace.yaml pnpm-workspace.yaml
COPY turbo.json turbo.json
COPY ./apps/backend ./apps/backend

RUN pnpm install
RUN pnpm run db:generate
RUN pnpm run build

EXPOSE 3001

CMD ["pnpm", "start:backend"]
