FROM node:22-alpine

RUN npm install -g pnpm

WORKDIR /app

ARG DATABASE_URL
COPY package.json package.json
COPY ./packages ./packages
COPY pnpm-lock.yaml pnpm-lock.yaml
COPY pnpm-workspace.yaml pnpm-workspace.yaml
COPY turbo.json turbo.json
COPY ./apps/web ./apps/web

RUN pnpm install
RUN pnpm run db:generate
RUN DATABASE_URL=${DATABASE_URL} pnpm run build

EXPOSE 3000

CMD ["pnpm", "start:web"]
