# Build the docker image
# Push the docker image to docker hub
# SSH into our VM and start the new image

name : deploy
on:
    push:
        branches: [ main ]
jobs:
    build:
        runs-on: ubuntu-latest
        steps:  
        - name: checkout
          uses: actions/checkout@v2
          with: 
            fetch-depth: 0  # Fetch all commits and branches (full history)

        - name: docker login
          uses: docker/login-action@v2
          with: 
                username: ${{ secrets.DOCKER_USERNAME }}
                password: ${{ secrets.DOCKER_PASSWORD }}
            
        - name: Build and push
          uses: docker/build-push-action@v4
          with:
            context: .
            file: ./docker/dockerfile.backend
            push: true
            tags: gaurav1149/todos-app-backend:${{ github.sha}}

